# 数据集配置文件
# 包含所有数据集相关的参数设置

dataset:
  # 数据路径配置
  data_root: './datasets/fill50k'
  json_file: 'prompt.json'
  
  # 图像处理参数
  image_size: 512
  
  # 数据加载参数
  batch_size: 8
  num_workers: 4
  shuffle: true
  pin_memory: true
  
  # 数据归一化参数
  source_normalization: [0, 1]  # [min, max] for source images
  target_normalization: [-1, 1]  # [min, max] for target images
  
  # 数据增强参数（可选）
  # augmentations:
  #   horizontal_flip: false
  #   vertical_flip: false
  #   rotation: 0
  #   brightness: 0.1
  #   contrast: 0.1
  
  # 验证集配置（可选）
  # validation:
  #   split_ratio: 0.1
  #   random_seed: 42
  
  # 缓存配置（可选）
  # cache:
  #   enable: false
  #   cache_dir: './cache' 