# SD 1.5 配置
model:
  config_path: './models/cldm_v15.yaml'
  resume_path: './models/controlnet/control_sd15_init.ckpt'
  sd_model_path: './models/stable-diffusion/v1-5-pruned.ckpt'
  learning_rate: 8e-6
  sd_locked: true
  only_mid_control: false

# 数据集配置引用（默认）
dataset: './configs/datasets/dataset_config_raining.yaml'

training:
  log_dir: './lightning_logs'
  image_log_dir: './image_log'
  gpus: 1
  precision: 32
  max_epochs: 10
  logger_freq: 300
  log_every_n_steps: 10
  val_check_interval: 1000
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0