# SD 1.5 配置
model:
  config_path: './models/cldm_v15.yaml'
  resume_path: './models/controlnet/control_sd15_init.ckpt'
  sd_model_path: './models/stable-diffusion/v1-5-pruned.ckpt'
  learning_rate: 8e-6
  sd_locked: true
  only_mid_control: false

dataset:
  data_root: './dataset/fill50k'
  json_file: 'prompt.json'
  image_size: 512
  batch_size: 8
  num_workers: 4
  shuffle: true
  pin_memory: true
  source_normalization: [0, 1]  # [min, max] for source images
  target_normalization: [-1, 1]  # [min, max] for target images

training:
  max_epochs: 10
  precision: 32
  gpus: 1
  logger_freq: 300
  log_every_n_steps: 10
  val_check_interval: 1000
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0

output:
  log_dir: './lightning_logs'
  image_log_dir: './image_log' 